"""Narrow frozen-legacy evidence and typed migration admission boundary.

The package inventories evidence first, then admits only selected ``nodes.jsonl``
current-state candidates through explicit legacy-admission transitions.  It does
not replay legacy history.  Relationship admission is limited to conservative,
stable-ID ``edges.jsonl`` candidates with namespaced endpoint aliases.  Legacy
embedding admission is separately conservative: it preserves only complete
object-revision-linked evidence chains as UNKNOWN, non-usable representations.
Identity admission recognizes only the current durable workspace-agent
``identity.json`` and workspace ``seed.json`` definition shapes, with no
memory dependency; derived ``character_state.json`` remains evidence.  It does
Motif admission recognizes only the current workspace/domain ``motifs.json``
registry and atomically admits its resolved EID memberships; motif events
remain evidence only.
Deep-memory admission recognizes only selected workspace-agent
``deep_memory/memories.jsonl`` records corroborated by imported source export
markers; it preserves those captures as non-READY representations.
Proposal admission recognizes only frozen ``proposals.jsonl`` submissions and
uses paired proposal-event evidence solely to capture their effective status.
Integrated rehearsal verifies those existing families in dependency order using
only synthetic frozen snapshots; it creates no live migration wiring.
"""

from .inventory import InventoryArtifact, InventorySnapshot, get_inventory, inventory_snapshot
from .admission import (
    LegacyEdgeAdmissionRun,
    LegacyNodeAdmissionRun,
    LegacyObjectAdmissionResult,
    LegacyRelationshipAdmissionResult,
    NativeLegacyObjectAdmissionService,
    NativeLegacyRelationshipAdmissionService,
)
from .representation_admission import (
    LegacyEmbeddingAdmissionRun,
    LegacyRepresentationAdmissionResult,
    NativeLegacyRepresentationAdmissionService,
)
from .identity_admission import (
    LegacyIdentityAdmissionResult,
    LegacyIdentityAdmissionRun,
    NativeLegacyIdentityAdmissionService,
)
from .motif_admission import (
    LegacyMotifAdmissionResult,
    LegacyMotifAdmissionRun,
    LegacyMotifMembershipResult,
    NativeLegacyMotifAdmissionService,
)
from .deep_memory_admission import (
    LegacyDeepMemoryAdmissionResult,
    LegacyDeepMemoryAdmissionRun,
    NativeLegacyDeepMemoryAdmissionService,
)
from .proposal_admission import (
    LegacyProposalAdmissionResult,
    LegacyProposalAdmissionRun,
    NativeLegacyProposalAdmissionService,
)
from .rehearsal import (
    ArtifactCoverage,
    FamilyAdmissionCount,
    MigrationRehearsalConfig,
    MigrationRehearsalReport,
    NativeLegacyMigrationRehearsal,
)
from .snapshot import (
    LegacyArtifact,
    LegacySnapshotManifest,
    SnapshotVerification,
    create_snapshot_manifest,
    load_snapshot_manifest,
    verify_snapshot,
)
from .runtime_readiness import (
    CoreRuntimeReadiness,
    EIDSideStoreReadiness,
    GovernanceEvidenceReadiness,
    LegacyCaptureReadiness,
    LegacyVectorStrategy,
    LifecycleEvidenceReadiness,
    MigrationRuntimeReadinessRequest,
    MigrationRuntimeReadinessReport,
    MigrationRuntimeScopePlan,
    MotifRuntimeReadiness,
    MotifRuntimeReadinessItem,
    NativeMigrationRuntimeReadinessPreflight,
    ObjectRuntimeReadiness,
    ObjectRuntimeReadinessItem,
    ProvenanceEvidenceReadiness,
    ScopePlanReadiness,
    SideStoreDisposition,
    SideStoreReadinessItem,
)
from .runtime_normalization import (
    MigrationRuntimeNormalizationRefused,
    MigrationRuntimeNormalizationRequest,
    MigrationRuntimeNormalizationResult,
    NativeMigrationRuntimeNormalizationService,
    PreparedLegacyMemoryNormalization,
)
from .runtime_representation_bootstrap import (
    MigrationRuntimeRepresentationBootstrapRefused,
    MigrationRuntimeRepresentationBootstrapRequest,
    MigrationRuntimeRepresentationBootstrapResult,
    NativeMigrationRuntimeRepresentationBootstrapService,
    PreparedLegacyCaptureRepresentationBootstrap,
)
from .runtime_reembedding_bootstrap import (
    MigrationRuntimeReembeddingBootstrapRefused,
    MigrationRuntimeReembeddingBootstrapRequest,
    MigrationRuntimeReembeddingBootstrapResult,
    NativeMigrationRuntimeReembeddingBootstrapService,
    PreparedRuntimeReembeddingBootstrap,
)
from .runtime_motif_projection import (
    MigrationRuntimeMotifProjectionRefused,
    MigrationRuntimeMotifProjectionRequest,
    MigrationRuntimeMotifProjectionResult,
    NativeMigrationRuntimeMotifProjectionService,
    PreparedLegacyMotifRuntimeProjection,
)
from .runtime_motif_regeometry_projection import (
    MigrationRuntimeMotifRegeometryProjectionRefused,
    MigrationRuntimeMotifRegeometryProjectionRequest,
    MigrationRuntimeMotifRegeometryProjectionResult,
    NativeMigrationRuntimeMotifRegeometryProjectionService,
    PreparedLegacyMotifRuntimeRegeometryProjection,
)
from .workspace_runtime_readiness import (
    MemoryNormalizationLineage,
    MotifProjectionLineage,
    NativeWorkspaceRuntimeReadiness,
    RetainedSideStoreEIDObservation,
    RetainedSideStoreEIDObservationState,
    RetainedSideStoreEIDObservationStatus,
    RetainedSideStoreEIDReference,
    WorkspaceMemoryReadinessItem,
    WorkspaceMotifReadinessItem,
    WorkspaceNativeEmbedderIdentity,
    WorkspaceNativeFeaturePosture,
    WorkspaceNativeReadinessVerdict,
    WorkspaceNativeRuntimeReadinessReport,
    WorkspaceNativeRuntimeReadinessRequest,
    WorkspaceReadinessBlockerClass,
    WorkspaceSideStoreReadinessItem,
)
from .existing_workspace_admission import (
    ExistingWorkspaceAdmissionDescriptor,
    ExistingWorkspaceAdmissionRefused,
    ExistingWorkspaceAdmissionState,
    ExistingWorkspaceNativeAdmissionRequest,
    ExistingWorkspaceNativeAdmissionResult,
    ExistingWorkspaceNativeAdmissionService,
    RecoveredExistingWorkspaceNativeReaders,
    RecoveredExistingWorkspaceNativeRuntime,
    load_existing_workspace_admission_descriptor,
    recover_existing_workspace_native_runtime,
)
from .existing_workspace_multi_scope_admission import (
    ExistingWorkspaceMultiScopeAdmissionRefused,
    ExistingWorkspaceMultiScopeAdmissionState,
    ExistingWorkspaceNativeLanePlan,
    ExistingWorkspaceNativeMultiScopeAdmissionRequest,
    ExistingWorkspaceNativeMultiScopeDescriptor,
    ExistingWorkspaceNativeMultiScopeLaneResult,
    ExistingWorkspaceNativeMultiScopeAdmissionResult,
    ExistingWorkspaceNativeMultiScopeSnapshotWitness,
    ExistingWorkspaceNativeMultiScopePreparedAdmission,
    ExistingWorkspaceNativeMultiScopeAdmissionService,
    RecoveredActiveExistingWorkspaceNativeMultiScopeScope,
    RecoveredExistingWorkspaceNativeMultiScopeReaders,
    RecoveredExistingWorkspaceNativeMultiScopeScope,
    RecoveredExistingWorkspaceNativeMultiScopeRuntime,
    load_existing_workspace_multi_scope_admission_descriptor,
    recover_active_existing_workspace_native_multi_scope_runtime,
    recover_existing_workspace_native_multi_scope_runtime,
)
from .character_seed_normalization import (
    MigrationCharacterSeedNormalizationRefused,
    MigrationCharacterSeedNormalizationRequest,
    NativeMigrationCharacterSeedNormalizationService,
    PreparedCharacterSeedNormalization,
)
from .root_scope import RootScopeKey, RootScopeKeyError, RootScopeKind
from .explicit_source_evidence import (
    EvidenceAbsenceReason,
    EvidenceOwnerBoundary,
    EvidenceOwnerBoundaryKind,
    EvidencePresenceExpectation,
    EvidenceSemanticRole,
    ExplicitSourceEvidence,
    ExplicitSourceEvidenceDrift,
    ExplicitSourceEvidenceError,
    RootEvidenceManifest,
    RootEvidenceVerification,
    SourceOwnerClass,
    capture_present_source_evidence,
    load_explicit_source_manifest,
    verify_explicit_source_manifest,
    write_explicit_source_manifest,
)
from .root_admission_description import (
    CENSUS_AND_MANIFEST_REQUIRE_WRITER_FREEZE,
    DeclaredUnmaterializedDomain,
    ExpectedRootCensus,
    ExternalOwnerObservation,
    ExternalOwnerObservationKind,
    GeometryDerivedExternalStateDisposition,
    IdentityOnlyAgentObservation,
    MaterializedRootScopePlan,
    MaterializedScopePosture,
    RepresentationDispositionCount,
    RootAdmissionDescriptionError,
    RootFeaturePosture,
    RootNativeProductionAdmissionDescription,
    RootRepresentationDisposition,
    SEMANTIC_ADAPTER_OWNERSHIP_DOES_NOT_EQUAL_DURABLE_STORE_OWNERSHIP,
    WorkspaceRootAdmissionPlan,
    WorkspaceTopologyCounts,
    WriterFreezeEvidenceState,
    representation_identity_matches_target,
)

__all__ = [
    "InventoryArtifact",
    "InventorySnapshot",
    "ArtifactCoverage",
    "FamilyAdmissionCount",
    "LegacyEdgeAdmissionRun",
    "LegacyEmbeddingAdmissionRun",
    "LegacyDeepMemoryAdmissionResult",
    "LegacyDeepMemoryAdmissionRun",
    "LegacyIdentityAdmissionResult",
    "LegacyIdentityAdmissionRun",
    "LegacyMotifAdmissionResult",
    "LegacyMotifAdmissionRun",
    "LegacyMotifMembershipResult",
    "LegacyProposalAdmissionResult",
    "LegacyProposalAdmissionRun",
    "LegacyNodeAdmissionRun",
    "LegacyObjectAdmissionResult",
    "LegacyRelationshipAdmissionResult",
    "LegacyRepresentationAdmissionResult",
    "LegacyArtifact",
    "LegacySnapshotManifest",
    "NativeLegacyObjectAdmissionService",
    "NativeLegacyIdentityAdmissionService",
    "NativeLegacyMotifAdmissionService",
    "NativeLegacyRelationshipAdmissionService",
    "NativeLegacyRepresentationAdmissionService",
    "NativeLegacyDeepMemoryAdmissionService",
    "NativeLegacyProposalAdmissionService",
    "MigrationRehearsalConfig",
    "MigrationRehearsalReport",
    "NativeLegacyMigrationRehearsal",
    "SnapshotVerification",
    "create_snapshot_manifest",
    "get_inventory",
    "inventory_snapshot",
    "load_snapshot_manifest",
    "verify_snapshot",
    "CoreRuntimeReadiness",
    "EIDSideStoreReadiness",
    "GovernanceEvidenceReadiness",
    "LegacyCaptureReadiness",
    "LegacyVectorStrategy",
    "LifecycleEvidenceReadiness",
    "MigrationRuntimeReadinessRequest",
    "MigrationRuntimeReadinessReport",
    "MigrationRuntimeScopePlan",
    "MotifRuntimeReadiness",
    "MotifRuntimeReadinessItem",
    "NativeMigrationRuntimeReadinessPreflight",
    "ObjectRuntimeReadiness",
    "ObjectRuntimeReadinessItem",
    "ProvenanceEvidenceReadiness",
    "ScopePlanReadiness",
    "SideStoreDisposition",
    "SideStoreReadinessItem",
    "MigrationRuntimeNormalizationRefused",
    "MigrationRuntimeNormalizationRequest",
    "MigrationRuntimeNormalizationResult",
    "NativeMigrationRuntimeNormalizationService",
    "PreparedLegacyMemoryNormalization",
    "MigrationRuntimeRepresentationBootstrapRefused",
    "MigrationRuntimeRepresentationBootstrapRequest",
    "MigrationRuntimeRepresentationBootstrapResult",
    "NativeMigrationRuntimeRepresentationBootstrapService",
    "PreparedLegacyCaptureRepresentationBootstrap",
    "MigrationRuntimeReembeddingBootstrapRefused",
    "MigrationRuntimeReembeddingBootstrapRequest",
    "MigrationRuntimeReembeddingBootstrapResult",
    "NativeMigrationRuntimeReembeddingBootstrapService",
    "PreparedRuntimeReembeddingBootstrap",
    "MigrationRuntimeMotifProjectionRefused",
    "MigrationRuntimeMotifProjectionRequest",
    "MigrationRuntimeMotifProjectionResult",
    "NativeMigrationRuntimeMotifProjectionService",
    "PreparedLegacyMotifRuntimeProjection",
    "MigrationRuntimeMotifRegeometryProjectionRefused",
    "MigrationRuntimeMotifRegeometryProjectionRequest",
    "MigrationRuntimeMotifRegeometryProjectionResult",
    "NativeMigrationRuntimeMotifRegeometryProjectionService",
    "PreparedLegacyMotifRuntimeRegeometryProjection",
    "MemoryNormalizationLineage",
    "MotifProjectionLineage",
    "NativeWorkspaceRuntimeReadiness",
    "RetainedSideStoreEIDObservation",
    "RetainedSideStoreEIDObservationState",
    "RetainedSideStoreEIDObservationStatus",
    "RetainedSideStoreEIDReference",
    "WorkspaceMemoryReadinessItem",
    "WorkspaceMotifReadinessItem",
    "WorkspaceNativeEmbedderIdentity",
    "WorkspaceNativeFeaturePosture",
    "WorkspaceNativeReadinessVerdict",
    "WorkspaceNativeRuntimeReadinessReport",
    "WorkspaceNativeRuntimeReadinessRequest",
    "WorkspaceReadinessBlockerClass",
    "WorkspaceSideStoreReadinessItem",
    "ExistingWorkspaceAdmissionDescriptor",
    "ExistingWorkspaceAdmissionRefused",
    "ExistingWorkspaceAdmissionState",
    "ExistingWorkspaceNativeAdmissionRequest",
    "ExistingWorkspaceNativeAdmissionResult",
    "ExistingWorkspaceNativeAdmissionService",
    "RecoveredExistingWorkspaceNativeReaders",
    "RecoveredExistingWorkspaceNativeRuntime",
    "load_existing_workspace_admission_descriptor",
    "recover_existing_workspace_native_runtime",
    "ExistingWorkspaceMultiScopeAdmissionRefused",
    "ExistingWorkspaceMultiScopeAdmissionState",
    "ExistingWorkspaceNativeLanePlan",
    "ExistingWorkspaceNativeMultiScopeAdmissionRequest",
    "ExistingWorkspaceNativeMultiScopeDescriptor",
    "ExistingWorkspaceNativeMultiScopeLaneResult",
    "ExistingWorkspaceNativeMultiScopeAdmissionResult",
    "ExistingWorkspaceNativeMultiScopeSnapshotWitness",
    "ExistingWorkspaceNativeMultiScopePreparedAdmission",
    "ExistingWorkspaceNativeMultiScopeAdmissionService",
    "RecoveredActiveExistingWorkspaceNativeMultiScopeScope",
    "RecoveredExistingWorkspaceNativeMultiScopeReaders",
    "RecoveredExistingWorkspaceNativeMultiScopeScope",
    "RecoveredExistingWorkspaceNativeMultiScopeRuntime",
    "load_existing_workspace_multi_scope_admission_descriptor",
    "recover_active_existing_workspace_native_multi_scope_runtime",
    "recover_existing_workspace_native_multi_scope_runtime",
    "MigrationCharacterSeedNormalizationRefused",
    "MigrationCharacterSeedNormalizationRequest",
    "NativeMigrationCharacterSeedNormalizationService",
    "PreparedCharacterSeedNormalization",
    "RootScopeKey",
    "RootScopeKeyError",
    "RootScopeKind",
    "EvidenceAbsenceReason",
    "EvidenceOwnerBoundary",
    "EvidenceOwnerBoundaryKind",
    "EvidencePresenceExpectation",
    "EvidenceSemanticRole",
    "ExplicitSourceEvidence",
    "ExplicitSourceEvidenceDrift",
    "ExplicitSourceEvidenceError",
    "RootEvidenceManifest",
    "RootEvidenceVerification",
    "SourceOwnerClass",
    "capture_present_source_evidence",
    "load_explicit_source_manifest",
    "verify_explicit_source_manifest",
    "write_explicit_source_manifest",
    "CENSUS_AND_MANIFEST_REQUIRE_WRITER_FREEZE",
    "DeclaredUnmaterializedDomain",
    "ExpectedRootCensus",
    "ExternalOwnerObservation",
    "ExternalOwnerObservationKind",
    "GeometryDerivedExternalStateDisposition",
    "IdentityOnlyAgentObservation",
    "MaterializedRootScopePlan",
    "MaterializedScopePosture",
    "RepresentationDispositionCount",
    "RootAdmissionDescriptionError",
    "RootFeaturePosture",
    "RootNativeProductionAdmissionDescription",
    "RootRepresentationDisposition",
    "SEMANTIC_ADAPTER_OWNERSHIP_DOES_NOT_EQUAL_DURABLE_STORE_OWNERSHIP",
    "WorkspaceRootAdmissionPlan",
    "WorkspaceTopologyCounts",
    "WriterFreezeEvidenceState",
    "representation_identity_matches_target",
]
