@echo off
setlocal

cd /d "%~dp0\.."

set TORMENT_PROFILE=companion

set TORMENT_DATA_DIR=%CD%\data\lived_use\eira_voss\a0
set TORMENT_TEST_CONDITION=a0
set TORMENT_SERVER_LAUNCHER_PATH=%CD%\examples\lived_use_a0_server.cmd
set TORMENT_SQLITE_INDEX_ENABLE=1

set TORMENT_CHARACTER_ENABLE=1
set TORMENT_THINKING_ADVISORY=1
set TORMENT_SPINE_ENABLE=1
set TORMENT_IDENTITY_SENSITIVE=1

set TORMENT_COMPRESS_ENABLE=0
set TORMENT_ARCHIVE_RECALL=0
set TORMENT_LIVE_SOCIAL=0
set TORMENT_CONTEXTUAL_ABSTENTION=0

set TORMENT_SRG_ENABLE=0
set TORMENT_SRG_COGNITION=0
set TORMENT_HIVEMIND_ENABLE=0

set TORMENT_COGNITION_SHAPING_V2=0
set TORMENT_COGNITION_CORE_SHAPING_V1=0
set TORMENT_GEOMETRIC_MEMORY_SHAPING_V1=0
set TORMENT_GEOMETRIC_RELATIONAL_PROMINENCE_SHAPING_V1=0
set TORMENT_RELATIONAL_AMBIGUITY_PROMINENCE_V1=0
set TORMENT_AMBIGUITY_CONTEXT_DIVERSITY_V1=0
set TORMENT_PARTICIPATION_GUIDANCE_V1=0

set TORMENT_EMBED_PROVIDER=st
set TORMENT_EMBED_MODEL=BAAI/bge-small-en-v1.5
set TORMENT_EMBED_DEVICE=cpu
set TORMENT_EMBED_STRICT=1

"C:\Users\Notandi\miniconda3\envs\torment\python.exe" -m torment_service

endlocal
