# domain_policies.py
from __future__ import annotations
from typing import Dict, Any

DEFAULT_DOMAIN_POLICIES: Dict[str, Dict[str, Any]] = {
    "research": {
        "auto_propose_max_per_window": 8,
        "auto_propose_min_gap_s": 10,
        "auto_propose_min_promotion": 0.78,
        "auto_propose_min_strength": 0.80,
        "auto_propose_min_confidence": 0.70,
        "auto_propose_require_novelty": False,
        "shared_min_distinct_agents": 2,
        "bridge_peek_requires_approval": False,        "motif_entropy_target_n": 24,
        "motif_entropy_high": 0.72,
        "motif_merge_similarity": 0.93,
        "motif_merge_max_suggestions": 20,
        "auto_merge_motifs": False,
        "auto_merge_entropy_trigger": 0.80,
    },
    "engineering": {
        "auto_propose_max_per_window": 6,
        "auto_propose_min_gap_s": 15,
        "auto_propose_min_promotion": 0.80,
        "auto_propose_min_strength": 0.82,
        "auto_propose_min_confidence": 0.72,
        "auto_propose_require_novelty": False,
        "shared_min_distinct_agents": 2,
        "bridge_peek_requires_approval": False,        "motif_entropy_target_n": 24,
        "motif_entropy_high": 0.72,
        "motif_merge_similarity": 0.93,
        "motif_merge_max_suggestions": 20,
        "auto_merge_motifs": False,
        "auto_merge_entropy_trigger": 0.80,
    },
    "operations": {
        "auto_propose_max_per_window": 3,
        "auto_propose_min_gap_s": 30,
        "auto_propose_min_promotion": 0.85,
        "auto_propose_min_strength": 0.85,
        "auto_propose_min_confidence": 0.80,
        "auto_propose_require_novelty": True,
        "shared_min_distinct_agents": 3,
        "bridge_peek_requires_approval": True,        "motif_entropy_target_n": 24,
        "motif_entropy_high": 0.72,
        "motif_merge_similarity": 0.93,
        "motif_merge_max_suggestions": 20,
        "auto_merge_motifs": False,
        "auto_merge_entropy_trigger": 0.80,
    },
    "creative": {
        "auto_propose_max_per_window": 10,
        "auto_propose_min_gap_s": 8,
        "auto_propose_min_promotion": 0.74,
        "auto_propose_min_strength": 0.78,
        "auto_propose_min_confidence": 0.60,
        "auto_propose_require_novelty": False,
        "shared_min_distinct_agents": 2,
        "bridge_peek_requires_approval": False,        "motif_entropy_target_n": 24,
        "motif_entropy_high": 0.72,
        "motif_merge_similarity": 0.93,
        "motif_merge_max_suggestions": 20,
        "auto_merge_motifs": True,
        "auto_merge_entropy_trigger": 0.80,
    },
    "meta": {
        "auto_propose_max_per_window": 2,
        "auto_propose_min_gap_s": 60,
        "auto_propose_min_promotion": 0.90,
        "auto_propose_min_strength": 0.90,
        "auto_propose_min_confidence": 0.85,
        "auto_propose_require_novelty": True,
        "shared_min_distinct_agents": 3,
        "bridge_peek_requires_approval": True,        "motif_entropy_target_n": 24,
        "motif_entropy_high": 0.72,
        "motif_merge_similarity": 0.93,
        "motif_merge_max_suggestions": 20,
        "auto_merge_motifs": False,
        "auto_merge_entropy_trigger": 0.80,
    },
    # Single-agent / companion default domain.
    # Relaxed thresholds — one agent's memories don't need multi-agent governance.
    "personal": {
        "auto_propose_max_per_window": 12,
        "auto_propose_min_gap_s": 5,
        "auto_propose_min_promotion": 0.70,
        "auto_propose_min_strength": 0.75,
        "auto_propose_min_confidence": 0.55,
        "auto_propose_require_novelty": False,
        "shared_min_distinct_agents": 1,
        "bridge_peek_requires_approval": False,
        "motif_entropy_target_n": 24,
        "motif_entropy_high": 0.72,
        "motif_merge_similarity": 0.93,
        "motif_merge_max_suggestions": 20,
        "auto_merge_motifs": True,
        "auto_merge_entropy_trigger": 0.80,
    },
}
